id: P003197
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8049
  title: གསུང་འབུམ། སེ་ར་མཁའ་འགྲོ་བདེ་ཆེན་བདེ་བའི་རྡོ་རྗེ།
  author: ''
  volumes:
    6a441b027e55430fbe79f0b995671f5d:
      image_group_id: I8LS20808
      title: ''
      volume_number: 1
      total_pages: 420
    6b80515b801c4ddcad78ad2094a87852:
      image_group_id: I8LS20809
      title: ''
      volume_number: 2
      total_pages: 292
    387c6a21f0eb4fe194d1593e690b4a72:
      image_group_id: I8LS20810
      title: ''
      volume_number: 3
      total_pages: 352
    92a47eab3d8c4dbaa922f10179414702:
      image_group_id: I8LS20811
      title: ''
      volume_number: 4
      total_pages: 300
    46e6b35e7e2c4f9b89721635b3ded7d1:
      image_group_id: I8LS20812
      title: ''
      volume_number: 5
      total_pages: 312
    a43c17c2066a413687d1613467dab7bc:
      image_group_id: I8LS20813
      title: ''
      volume_number: 6
      total_pages: 216
    b9fd413b17d64df0994034f107894d27:
      image_group_id: I8LS20814
      title: ''
      volume_number: 7
      total_pages: 242
