id: ICC87CF32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:13:13+00:00'
last_modified: '2022-06-07T18:20:30.489595+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8049
  title: གསུང་འབུམ། སེ་ར་མཁའ་འགྲོ་བདེ་ཆེན་བདེ་བའི་རྡོ་རྗེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '6522':
      image_group_id: I8LS20808
      title: ''
      total_pages: 420
      order: 1
      base_file: 6522.txt
    C3F0:
      image_group_id: I8LS20809
      title: ''
      total_pages: 292
      order: 2
      base_file: C3F0.txt
    47F7:
      image_group_id: I8LS20810
      title: ''
      total_pages: 352
      order: 3
      base_file: 47F7.txt
    E92E:
      image_group_id: I8LS20811
      title: ''
      total_pages: 300
      order: 4
      base_file: E92E.txt
    42F7:
      image_group_id: I8LS20812
      title: ''
      total_pages: 312
      order: 5
      base_file: 42F7.txt
    74E7:
      image_group_id: I8LS20813
      title: ''
      total_pages: 216
      order: 6
      base_file: 74E7.txt
    819A:
      image_group_id: I8LS20814
      title: ''
      total_pages: 242
      order: 7
      base_file: 819A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
